name: CD

on:
  workflow_dispatch:

env:
  TARGET_HOST: zeta.cs.petrsu.ru
  TARGET_USER: vadim
  TARGET_DIR: /home/03/vadim/my/2023/itmo-instr/deploys


jobs:

#  check:
#    uses: ./.github/workflows/ci.yml

  deploy:
    name: deploy service
    runs-on: ubuntu-latest
#    needs: check
    
    steps:
    
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Setup ssh agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.TEST_SSH_PRIVATE_KEY }}
      
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "github.workspace = ${{ github.workspace }}"
      - run: echo "GITHUB_RUN_ID = $GITHUB_RUN_ID"
        
